# Generated by Django 4.2.4 on 2023-08-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onetimecode",
            options={
                "verbose_name": "Одноразовый код",
                "verbose_name_plural": "Одноразовые коды",
            },
        ),
    ]
