# Generated by Django 4.2.4 on 2023-08-09 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adverts", "0002_add_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
