# Generated by Django 4.2.4 on 2023-08-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("adverts", "0004_add_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="review",
            new_name="advert",
        ),
        migrations.AlterField(
            model_name="reply",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор отклика",
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="text",
            field=models.TextField(verbose_name="Текст отклика"),
        ),
    ]
