# Generated by Django 4.2.4 on 2023-08-13 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adverts", "0005_rename_review_reply_advert_alter_reply_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(1, 1, 1, 0, 0),
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
    ]
