# Generated by Django 4.2.4 on 2023-08-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adverts", "0006_reply_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="Принято"),
        ),
    ]
